[package]
name = "fastforward"
version = "0.0.1"
authors = ["Brian Mason <bpmason1@hotmail.com>"]
repository = "https://github.com/bpmason1/fastforward"

edition = "2018"

exclude = [
	"*.md",
	"tests/*"
]
include = [
	"src/**/*",
	"Cargo.toml",
	"README.md"
]

readme = "README.md"
keywords = [
	"proxy",
]
description = """
A library for implementing custom reverse proxies.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bottle = { path = "./bottle" }
http = "0.2.0"
lazy_static = "1.4.0"
nom = { version = "5.0.1", features = ["regexp"] }
rayon = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
