[package]
name = "fastforward"
version = "0.0.1"
authors = ["Brian Mason <bpmason1@hotmail.com>"]
repository = "https://github.com/bpmason1/fastforward"

edition = "2018"

exclude = [
	"*.md",
	"tests/*"
]
include = [
	"src/**/*",
	"Cargo.toml",
	"README.md"
]

readme = "README.md"
keywords = [
	"proxy",
]
description = """
A library for implementing custom reverse proxies.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.12.35"

